name: Validate meta data

on:
  pull_request:
    branches: [main]
    paths:
      - "meta.yaml"
  push:
    branches: [main]
    paths:
      - "meta.yaml"

permissions:
  contents: read

jobs:
  validate-meta-data:
    runs-on: ubuntu-latest
    name: Validate meta data file
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: mikefarah/yq@6251e95af8df3505def48c71f3119836701495d6 # v4.47.2
        with:
          cmd: yq -o=json '.' meta.yaml > meta.json
      - name: Validate meta data
        uses: cardinalby/schema-validator-action@2166123eb256fa40baef7e22ab1379708425efc7 # v3
        with:
          file: meta.json
          schema: meta.schema.json
